version: '3.8'

services:
  history-service:
    container_name: history-service
    build:
      context: .
      dockerfile: Dockerfile
    command: 'npm start'
    ports:
      - "5433:5433"
    volumes:
      - .:/app
    depends_on:
      - postgres-db9000


  postgres-db9000:
    image: postgres:latest
    container_name: submission-db
    environment:
      POSTGRES_DB: submission-db
      POSTGRES_USER: postgres-db
      POSTGRES_PASSWORD: postgres-db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "9000:5432"
