name: Lint Check

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Lint JavaScript Code
        run: |
          for service in frontend gateway matching-service question-service; do
            cd $service
            npm install
            npm run lint
            cd ..
          done

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Lint Python Code for user-service
        run: |
          cd user-service
          pip install -r requirements.txt
          flake8  # Use flake8 or any other Python linter you prefer
