apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: asia-southeast1-docker.pkg.dev/steam-bee-404110/peer-prep/frontend
          env:
            - name: NEXT_PUBLIC_MATCHING_SVC_URI
              value: http://localhost:8001
            - name: NEXT_PUBLIC_QUESTION_SVC_URI
              value: http://localhost:5000
            - name: NEXT_PUBLIC_USER_SVC_URI
              value: http://localhost:8000
          ports:
            - containerPort: 3000
          resources: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: asia-southeast1-docker.pkg.dev/steam-bee-404110/peer-prep/api-gateway
          env:
            - name: MATCHING_BASE_URL
              value: http://matching-service:8001
            - name: QUESTION_BASE_URL
              value: http://question-service:5000
            - name: SECRET_KEY
              value: django-insecure-6&0xj1vstd4^_sgd#9vbn42bs4em$glhvkm5ba&8-(f8c$aa++
            - name: USER_BASE_URL
              value: http://user-service:8000 
          ports:
            - containerPort: 3001
          resources: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres-db
          image: postgres:15.4
          env:
            - name: POSTGRES_DB
              value: user_service
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          ports:
            - containerPort: 5432
          resources: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: asia-southeast1-docker.pkg.dev/steam-bee-404110/peer-prep/user-service
          env:
            - name: DATABASE_HOST
              value: postgres-db
            - name: DATABASE_NAME
              value: user_service
            - name: DATABASE_PASSWORD
              value: postgres
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USER
              value: postgres
            - name: DJANGO_DEBUG
              value: "True"
            - name: DJANGO_SECRET_KEY
              value: django-insecure-6&0xj1vstd4^_sgd#9vbn42bs4em&8-(f8c++
            - name: SECRET_KEY
              value: django-insecure-6&0xj1vstd4^_sgd#9vbn42bs4em$glhvkm5ba&8-(f8c$aa++
          ports:
            - containerPort: 8000
          resources: {}

---