apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - args:
            - npm
            - run
            - dev
          env:
            - name: NEXT_PUBLIC_MATCHING_SVC_URI
              value: http://localhost:8001
            - name: NEXT_PUBLIC_QUESTION_SVC_URI
              value: http://localhost:5000
            - name: NEXT_PUBLIC_USER_SVC_URI
              value: http://localhost:8000
          image: asia-southeast1-docker.pkg.dev/steam-bee-404110/peer-prep/frontend
          name: frontend
          ports:
            - containerPort: 3000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
