apiVersion: batch/v1
kind: Job
metadata:
  name: user-service-migrate
spec:
  template:
    spec:
      containers:
        - name: user-service
          image: asia-southeast1-docker.pkg.dev/steam-bee-404110/peer-prep/user-service:latest
          command: ["/bin/sh","-c"]
          args: ["python manage.py makemigrations && python manage.py migrate"]
          envFrom:
            - configMapRef:
                name: peerprep-config
      restartPolicy: Never
  backoffLimit: 5