apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: frontend

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: api-gateway

---
apiVersion: v1
kind: Service
  name: postgres-db
  namespace: default
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-db

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: user-service

---