# Generated by Django 4.2.5 on 2023-09-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_profile_id_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('normal user', 'Normal User')], default='normal user', max_length=20),
        ),
    ]
