version: '3.9'

services:
  # MongoDB services
  mongo-db:
    image: mongo:latest
    restart: always
    volumes: 
      - mongo_db:/data/db
    ports:
      - 27017:27017

  # Mode API service
  api:
    build: .
    ports: 
      - 5000:5000
    environment:
      DATABASE_URL: mongodb://mongo-db:27017/questions
    depends_on:
      - mongo-db

volumes: 
  mongo_db: {}